---
- name: Gather installed packages
  ansible.builtin.package_facts:

- name: Ensure that packages are installed
  when: amp_package not in ansible_facts.packages
  become: true
  ansible.builtin.apt:
    deb: "{{ amp_package_url }}"
    update_cache: true
    state: present
