---
- name: Install cisco amp
  when: amp_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

- name: Uninstall cisco amp
  when: amp_uninstall == true
  block:
    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
