---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ amp_package }}"
    autoremove: "{{ amp_autoremove }}"
    purge: "{{ amp_purge }}"
    state: absent
