---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ amp_autoremove }}"
    purge: "{{ amp_purge }}"
    state: absent
  loop: "{{ amp_packages }}"
